# -*- mode: ruby -*-
# vi: set ft=ruby :

vagrant_box = "generic/ubuntu2204"

Vagrant.configure("2") do |config|
    
  config.vm.define "hyper01" do |hyper01|
    hyper01.vm.box = vagrant_box
  end
  
  config.vm.define "hyper02" do |hyper02|
    hyper02.vm.box = vagrant_box
  end
  
end

system('vagrant ssh-config > ~/.ssh/config')
