# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.provider :libvirt do |libvirt|
    libvirt.management_network_name = "openstack-vlans"
    libvirt.management_network_address = "192.168.121.0/24"  # default
  end

  config.vm.box = "generic/ubuntu2204"
  
  # script
  $script = <<-SCRIPT
  # allow root ssh
  rm -rf /root/.ssh
  cp -r /home/vagrant/.ssh/ /root/

  # extend root disk
  lvextend -l +100%FREE /dev/ubuntu-vg/ubuntu-lv
  resize2fs /dev/ubuntu-vg/ubuntu-lv
  SCRIPT

  config.vm.define "hyper01" do |hyper01|
    hyper01.vm.provider :libvirt do |domain|
      domain.memory = 65536 
      domain.cpus = 6
      domain.machine_virtual_size = 150
    end
    hyper01.vm.hostname = "hyper01"
    hyper01.vm.network :private_network, :ip => '10.0.80.11', :libvirt__network_name => 'provider'
    hyper01.vm.provision "shell", inline: $script
  end
  
  config.vm.define "hyper02" do |hyper02|
    hyper02.vm.provider :libvirt do |domain|
      domain.memory = 65536
      domain.cpus = 6
      domain.machine_virtual_size = 150
    end
    hyper02.vm.hostname = "hyper02"
    hyper02.vm.network :private_network, :ip => '10.0.80.12', :libvirt__network_name => 'provider'
    hyper02.vm.provision "shell", inline: $script
  end

  config.trigger.after :up do |trigger|
    trigger.run = {inline: "bash -c 'vagrant ssh-config | sed \"s/User vagrant/User root/g\" > ~/.ssh/config'"}
  end

end

