# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    
  config.vm.box = "generic/ubuntu2204"
  
  # script
  $script = <<-SCRIPT
  rm -rf /root/.ssh
  cp -r /home/vagrant/.ssh/ /root/
  SCRIPT

  config.vm.define "hyper01" do |hyper01|
    hyper01.vm.provider :libvirt do |domain|
      domain.memory = 65536 
      domain.cpus = 6
      domain.machine_virtual_size = 150
    end
    hyper01.vm.provision "shell", inline: $script
  end
  
  config.vm.define "hyper02" do |hyper02|
    hyper02.vm.provider :libvirt do |domain|
      domain.memory = 65536
      domain.cpus = 6
      domain.machine_virtual_size = 150
    end
    hyper02.vm.provision "shell", inline: $script
  end

  config.trigger.after :up do |trigger|
    trigger.run = {inline: "bash -c 'vagrant ssh-config | sed \"s/User vagrant/User root/g\" > ~/.ssh/config'"}
  end

end

